# Org-domain DMARC record for the management zone (D-11).
# Written via the global-management provider generated by providers/regional.hcl.
# required_providers comes from the generated provider.tf — do not redeclare here.

variable "dns" {
  type = object({
    zonename   = string
    subdomains = list(string)
    ttl        = optional(number, 300)
  })
  description = "DNS/Host configuration (zonename drives the apex DMARC record)"
}

data "aws_route53_zone" "mgmt" {
  provider = aws.global-management
  name     = var.dns.zonename
}

# p=quarantine with relaxed alignment (aspf=r, adkim=r) so DKIM signatures
# from auth.<zonename> align with the org domain for subdomain sends.
resource "aws_route53_record" "apex_dmarc" {
  provider = aws.global-management
  zone_id  = data.aws_route53_zone.mgmt.zone_id
  name     = "_dmarc.${var.dns.zonename}"
  type     = "TXT"
  ttl      = 600
  records  = ["v=DMARC1; p=quarantine; rua=mailto:dmarc-reports@auth.${var.dns.zonename}; aspf=r; adkim=r;"]
}
